### ISSUE TITLE
The deploy not working

### ISSUE THREAD

**Issue by EliasSalom** [tyseerhen/tyseerhen-test#1]
I have been checked your deployment is not working, **and the weird thing is that you haven't checked your deploy**

**Comment by EliasSalom** [comment]
the issue is still on, you don't have to fix it, so please don't close any issue if you still not fixing it, OK!!

**Comment by tyseerhen** [comment]
hey elias @EliasSalom please return this repo to my own profile to fix the deploy

**Comment by EliasSalom** [comment]
done, it's yours now fix it !!!
